name: Update and deploy AddOn

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

env:
  ADDON_NAME: ${{ github.event.repository.name }}
  ADDON_ARCHIVE_NAME: ${{ github.event.repository.name }}.zip
  ESOUI_TOKEN: ${{ secrets.ADDON_UPDATE_API_TOKEN }}
  ZIP_EXCLUDE_FILE_PATH: $GITHUB_WORKSPACE/.github/excludeFiles.txt

jobs:
  updateAddon:
    name: Update and deploy ${{ github.event.repository.name }} to version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List all existing addons
        run: |
            curl -H "x-api-token: ${{ env.ESOUI_TOKEN }}" https://api.esoui.com/addons/list.json

      - name: Zip AddOn content
        run:  |
            7z a -xr@"${{ env.ZIP_EXCLUDE_FILE_PATH }}" ${{ env.ADDON_ARCHIVE_NAME }} ../${{ env.ADDON_NAME }}
      
      - name: Upload zip result to Github
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ADDON_NAME }} ${{ github.event.inputs.version }}
          path: ${{ env.ADDON_ARCHIVE_NAME }}
